# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

name: Onefuzz Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: oeciteam/oetools-full-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7 
      - name: Install pip
        run: |
          python3 -m pip install --upgrade pip
      - name: Install CMake
        run: |
          python3 -m pip install cmake
      - name: build
        run: |
          ./build.sh -c -i -d
      - name: submit onefuzz job
        env:
          ONEFUZZ_ENDPOINT: ${{ secrets.onefuzz_endpoint }}
          ONEFUZZ_CLIENT_ID: ${{ secrets.onefuzz_client_id }}
          ONEFUZZ_CLIENT_SECRET: ${{ secrets.onefuzz_client_secret }}
          ONEFUZZ_PAT: ${{ secrets.onefuzz_pat }}
        run: |
          set -ex
          pip3 install onefuzz==2.23.0
          sed -i s/INSERT_YOUR_PERSONAL_ACCESS_TOKEN_HERE/${ONEFUZZ_PAT}/ .github/workflows/github-issues.json
          onefuzz config --endpoint $ONEFUZZ_ENDPOINT --client_id $ONEFUZZ_CLIENT_ID --client_secret $ONEFUZZ_CLIENT_SECRET
          ./src/dynamic/scripts/onefuzz/run.sh
